version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0
    volumes:
      - orm_volume_mysql:/var/lib/mysql
    ports:
      - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - ${LOCAL_IP}:${DRAGONFLY_PORT}:6379
    volumes:
      - orm_volume_dragonfly:/data
volumes:
  orm_volume_mysql: {}
  orm_volume_dragonfly: {}
